### PR TITLE
Recipe updates for Perl packages for Shiny

### PR DESCRIPTION
**Pull request by jeanconn**
Recipe updates for Perl packages for shiny.

Largely this just sets these builds to 

 - use a provided perl package
 - use the anaconda compilers instead of system compilers to build the rest
 
Also cuts old pgplot

### CODE REVIEW

**Comment by taldcroft** [comment]
This is failing for me since it is expecting source packages as `file:///proj/sot/ska/pkgs/...`.  What's the build procedure for Mac?
```
(ska3-shiny) ➜  skare3-static git:(shiny) ./build.py
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.11
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from /Users/aldcroft/git/skare3-static/xtime/conda_build_config.yaml
INFO:conda_build.variants:Adding in variants from /Users/aldcroft/git/skare3-static/xtime/conda_build_config.yaml
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
Attempting to finalize metadata for xtime
INFO:conda_build.metadata:Attempting to finalize metadata for xtime
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
BUILD START: ['xtime-1.2.2-0.tar.bz2']
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done

## Package Plan ##

  environment location: /Users/aldcroft/git/skare3-static/builds/xtime_1593374239677/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho


The following NEW packages will be INSTALLED:

    cctools:            927.0.2-h5ba7a2e_4       
    clang:              10.0.0-default_hf57f61e_0
    clang_osx-64:       10.0.0-h05bbb7f_1        
    clangxx:            10.0.0-default_hf57f61e_0
    clangxx_osx-64:     10.0.0-h05bbb7f_1        
    compiler-rt:        10.0.0-h47ead80_0        
    compiler-rt_osx-64: 10.0.0-hbcc88fd_0        
    ld64:               450.3-h3c32e8a_4         
    libcxx:             10.0.0-1                 
    libllvm10:          10.0.0-h21ff451_0        
    llvm-openmp:        10.0.0-h28b9765_0        
    llvm-tools:         10.0.0-h21ff451_0        
    tapi:               1000.10.8-ha1b3eb9_0     

Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
Collecting package metadata (repodata.json): ...working... done
Solving environment: ...working... done
Source cache directory is: /Users/aldcroft/git/skare3-static/builds/src_cache
INFO:conda_build.source:Source cache directory is: /Users/aldcroft/git/skare3-static/builds/src_cache
INFO conda_build.source:download_to_cache(43): Source cache directory is: /Users/aldcroft/git/skare3-static/builds/src_cache
No hash (md5, sha1, sha256) provided for XTime-1.2.2.tar.gz.  Source download forced.  Add hash to recipe to use source cache.
WARNING:conda_build.source:No hash (md5, sha1, sha256) provided for XTime-1.2.2.tar.gz.  Source download forced.  Add hash to recipe to use source cache.
WARNING conda_build.source:download_to_cache(59): No hash (md5, sha1, sha256) provided for XTime-1.2.2.tar.gz.  Source download forced.  Add hash to recipe to use source cache.
Downloading source to cache: XTime-1.2.2.tar.gz
INFO:conda_build.source:Downloading source to cache: XTime-1.2.2.tar.gz
INFO conda_build.source:download_to_cache(66): Downloading source to cache: XTime-1.2.2.tar.gz
Downloading file:///proj/sot/ska/pkgs/XTime-1.2.2.tar.gz
INFO:conda_build.source:Downloading file:///proj/sot/ska/pkgs/XTime-1.2.2.tar.gz
INFO conda_build.source:download_to_cache(80): Downloading file:///proj/sot/ska/pkgs/XTime-1.2.2.tar.gz
Error: HTTP 404 CONNECTION FAILED for url <file:///proj/sot/ska/pkgs/XTime-1.2.2.tar.gz>
Elapsed: 00:00.000126

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
WARNING:conda_build.source:Error: HTTP 404 CONNECTION FAILED for url <file:///proj/sot/ska/pkgs/XTime-1.2.2.tar.gz>
Elapsed: 00:00.000126

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
WARNING conda_build.source:download_to_cache(84): Error: HTTP 404 CONNECTION FAILED for url <file:///proj/sot/ska/pkgs/XTime-1.2.2.tar.gz>
Elapsed: 00:00.000126

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Could not download file:///proj/sot/ska/pkgs/XTime-1.2.2.tar.gz
Traceback (most recent call last):
  File "./build.py", line 40, in <module>
    "--perl", "5.26.2", "--croot", build_dir, pkg])
  File "/Users/aldcroft/miniconda3/envs/ska3-shiny/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['conda', 'build', '--use-local', '--perl', '5.26.2', '--croot', './builds', 'xtime']' returned non-zero exit status 1.
```

**Comment by jeanconn** [comment]
I was hoping the build procedure for mac would "don't do it because the packages are already in the repo".  I just updated the file paths locally to match local ones on my mac.  In previous versions of the OS I'd just put those files in a /proj/sot/ska/pkgs on the build system.  It seemed not worth the effort on catalina (to make it let me make a /proj/sot/ska) and not worth a new process (env var or web source for pkgs or change to a local dir or whatever).

**Comment by jeanconn** [comment]
I put my silly steps in https://github.com/sot/skare3/wiki/Building-skare3-static-packages-on-OSX .  If we're going to do this more than once, obviously I'll fix the paths.  Also don't know if we require a newer SDK or even if we care about using the anaconda compilers.  Using them just seemed like the "right" thing for building conda packages, but I'm not 100% convinced it will save us trouble in the long term.  Also a question about if the recipes for Chandra.Time, xija, Ska.Numpy should be updated to use the anaconda compilers instead of system compilers on the Python/C package side.

**Comment by taldcroft** [comment]
Can we put these packages within `ASPECT/skare3-conda/skare3-static-pkgs`?  I feel better staying within that existing home for all things skare3.

**Comment by jeanconn** [comment]
I didn't really feel I had control of `ASPECT/skare3-conda` to put stuff there (wasn't sure if it was all going to be wiped out again etc) and these are both different (src packages for a different project) and supposedly static.

**Comment by taldcroft** [comment]
I tested this on Mac and looks good!

There are only *new* packages that get installed:
```
conda create -n shiny-tmp-perl2 -c file://$PWD/builds -c https://icxc.cfa.harvard.edu/aspect/ska3-conda/shiny -c defaults -c conda-forge ska3-flight-latest ska3-core-latest perl-app-cpanminus perl-core-deps perl-ska-classic

New packages:

  perl               pkgs/main/osx-64::perl-5.26.2-h4e221da_0
  perl-app-cpanminus builds/osx-64::perl-app-cpanminus-1.7044-pl526_0
  perl-core-deps     builds/osx-64::perl-core-deps-0.3-py38pl526h0a44026_0
  perl-ska-classic   builds/osx-64::perl-ska-classic-0.6-pl526_0
  pkg-config         pkgs/main/osx-64::pkg-config-0.29.2-h3efe00b_8
  zip                pkgs/main/osx-64::zip-3.0-hd605571_0
```

**Testing**
```
(shiny-tmp-perl) ➜  starcheck git:(master) ./sandbox_starcheck -dir ~/ska/data/mpcrit1/mplogs/2020/JUL2020/ofls 
```
Gives reasonable outputs, though need to do more careful comparison.

**Comment by jeanconn** [comment]
Thank Tom.  I updated https://github.com/sot/skare3/wiki/Notes:-building-skare3-static-packages-for-shiny with most of my last build process and such and it looks consistent with what you saw on the OSX side.  I don't know what you want to do for the final shiny repo but we should have pieces in place as needed.

**Review by taldcroft — APPROVED** [review]
Looks good to me!  :tada:  If there are any tiny loose ends we can revisit.

**Comment by jeanconn** [comment]
Thanks Tom :fireworks:

**Pull request merged**
